#!/bin/bash

echo "🚨 URGENT: Applying comprehensive database fixes to stop console flooding..."
echo ""
echo "This script will fix all 406 and 400 errors by:"
echo "1. ✅ Fixing users table RLS policies"
echo "2. ✅ Fixing games table RLS policies" 
echo "3. ✅ Creating default 'everything-else' game"
echo "4. ✅ Testing all fixes"
echo ""
echo "⚠️  IMPORTANT: You must run this SQL in Supabase Dashboard → SQL Editor"
echo ""
echo "📋 Copy and paste the contents of COMPREHENSIVE_FIX_ALL_ERRORS.sql into Supabase SQL Editor"
echo "📋 Then click 'Run' to execute the fix"
echo ""
echo "🎯 Expected results after running SQL:"
echo "   ✅ No more 406 errors for users table"
echo "   ✅ No more 406 errors for games table"
echo "   ✅ Clean console with minimal errors"
echo "   ✅ App will show landing page for returning users"
echo ""
echo "📁 SQL file location: $(pwd)/COMPREHENSIVE_FIX_ALL_ERRORS.sql"
echo ""
echo "🔗 Go to: https://supabase.com/dashboard/project/qajcxgkqloumogioomiz/sql"
echo ""
echo "Press Enter when you've applied the SQL fix..."
read -r
echo "✅ SQL fix applied! The console flooding should now be resolved."