#!/bin/bash

# AUTHENTICATION DEBUG SCRIPT
# This script helps debug authentication issues

echo "🔍 Authentication Debug Script"
echo "============================="
echo ""

echo "📋 Current Issues:"
echo "  ❌ Emails not getting added to Supabase"
echo "  ❌ Authentication flow going back to landing page"
echo "  ❌ Not sure if authentication happened"
echo ""

echo "🔍 Debugging Steps:"
echo ""
echo "Step 1 - Check Supabase Database:"
echo "  Go to Supabase Dashboard → SQL Editor"
echo "  Copy and paste the contents of DEBUG_AUTHENTICATION.sql"
echo "  Click 'Run' to check the results"
echo ""

echo "Step 2 - Check Browser Console:"
echo "  1. Open your app: http://localhost:5173"
echo "  2. Open browser console (F12)"
echo "  3. Look for these logs:"
echo "     - '🔐 Validating existing session...'"
echo "     - '🔐 Session validated successfully'"
echo "     - '✅ User authenticated, checking onboarding status...'"
echo "     - '🔍 Auth Debug:' (with user data)"
echo ""

echo "Step 3 - Check Authentication State:"
echo "  # In browser console, run:"
echo "  console.log('Auth state:', window.authService?.getAuthState());"
echo "  console.log('Current user:', window.authService?.getCurrentUserId());"
echo ""

echo "Step 4 - Check Local Storage:"
echo "  # In browser console, run:"
echo "  console.log('Auth method:', localStorage.getItem('otakonAuthMethod'));"
echo "  console.log('Skipped landing:', localStorage.getItem('otakonSkippedLanding'));"
echo ""

echo "Step 5 - Test Authentication Flow:"
echo "  1. Clear all data:"
echo "     localStorage.clear();"
echo "     location.reload();"
echo ""
echo "  2. Try signing in with Google/Discord"
echo "  3. Check if user gets created in Supabase"
echo ""

echo "🔧 Common Issues and Solutions:"
echo ""
echo "Issue 1 - No users in auth.users table:"
echo "  - Authentication providers not configured"
echo "  - OAuth redirect URLs not set up"
echo "  - Solution: Configure OAuth providers in Supabase Dashboard"
echo ""
echo "Issue 2 - Users in auth.users but not in public.users:"
echo "  - Trigger not working"
echo "  - RLS policies blocking insert"
echo "  - Solution: Check trigger and RLS policies"
echo ""
echo "Issue 3 - Authentication going back to landing page:"
echo "  - User data not loading (406 errors)"
echo "  - Landing page preference not set"
echo "  - Solution: Fix user data loading"
echo ""

echo "🧪 Quick Tests:"
echo ""
echo "Test 1 - Check if user exists:"
echo "  SELECT * FROM public.users WHERE email = 'your-email@example.com';"
echo ""
echo "Test 2 - Check auth users:"
echo "  SELECT * FROM auth.users WHERE email = 'your-email@example.com';"
echo ""
echo "Test 3 - Test trigger manually:"
echo "  -- This will test if the trigger works"
echo "  -- (Only run if you have a test auth user)"
echo ""

echo "📞 If you need help:"
echo "  1. Run DEBUG_AUTHENTICATION.sql first"
echo "  2. Check browser console logs"
echo "  3. Verify OAuth provider configuration"
echo "  4. Test with a fresh browser session"
echo ""

echo "🎯 Ready to debug! Start with Step 1 above."
